### ISSUE TITLE
Messages stored by MAM while gajim is offline are not shown

### ISSUE THREAD

**Issue by mapama** [kalkin/gajim-omemo#36] opened 2016-01-26 12:07 UTC
Steps to reproduce this issue:
- Start an OMEMO-encrypted conversation
- Go offline
- Send an encrypted message from another device
- Go online
- Go the chat history
  The sent message is not shown.

Expected behaviour: See the message in the chat history.

Tested with ejabberd 15.10 on Debian Jessie and MAM enabled.

Thanks for the development of this great plugin.

**Comment by lovetox** [comment] 2016-04-13 18:50
i cant reproduce this, im on jabber.at

if i go offline, and send a message from my phone using conversations, after i go online with gajim i get a notification with the message.

**Comment by mapama** [comment] 2016-04-13 20:53
You're right my steps to reproduce weren't precise enough. I had to exclude the scenario @lovetox described. I think @lovetox scenario is different because there is no other third client catching away the message while gajim is offline. In this case ejabberd stores the message as offline message and deliver it to gajim when coming online.

The situation that didn't work for me is as follows:
Bob has two devices, one computer running gajim and one mobile running conversations, gajim is offline while conversations is online. Now Alice sends a message to Bob. Bob receives the message in conversations. Then switches on gajim, but doesn't get the carbon copied message. Without omemo enabled he does. If you would like to test it with one account you have to use a third client. @lovetox  could you test this scenario on jabber.at please?

**Comment by lovetox** [comment] 2016-04-14 14:27
so do you get the message if gajim and conversations are online in both clients?

also are you using the current branch, or are you using the FTP version 0.4

i cant try this out right now.

**Comment by mapama** [comment] 2016-04-14 15:03
Yes if both clients are online I receive the message in both. I am using version 0.4. Right now I can't test it with the current branch.

**Comment by mapama** [comment] 2016-04-16 15:34
Ok, tested with the current branch but this doesn't matter. It doesn't work. Tested with two mobile clients running conversations and one client running gajim. Go offline with gajim send a message from one of the mobile clients. The second mobile client receive this message. Go online with gajim but the messages is missed in the chat history.

**Comment by exul** [comment] 2016-05-09 18:43
> Bob has two devices, one computer running gajim and one mobile running conversations, gajim is offline while conversations is online. Now Alice sends a message to Bob. Bob receives the message in conversations. Then switches on gajim, but doesn't get the carbon copied message.

I can reproduce this on my server that runs prosody:

```
# dpkg-query -l | grep prosody
ii  prosody                            0.9.4-1~bpo70+1                   amd64        Lightweight Jabber/XMPP server
```

I logged the output with `gajim -l gajim.plugin_system.omemo=DEBUG -v` you can see it here: https://gist.github.com/exul/7e751ed9b0b5ff7c5647c998f18c44ca

Gajim version is `0.16.5`

If you need an account or more information, just let me know.

**Comment by amenk** [comment] 2016-05-23 07:25
I am not sure if the bug is as described.

I have the following case:

Server = Ejabberd with MAM
1. Go offline in Gajim
2. Write in Conversations (Android) with OMEMO
3. Go online in Gajim
4. Open history in Gajim -> Message is there

But:

If a contact sends the message using Gajim with OMEMO, it is not stored in the MAM (verified using database dump in ejabberd). So it looks like Gajim does not push OMEMO messages to the MAM ?

**Comment by iNPUTmice** [comment] 2016-05-23 07:38
> So it looks like Gajim does not push OMEMO messages to the MAM ?

I'm not sure if this is related to the rest of the thread but this can be solved by adding the <store/> hint to outgoing messages.

**Comment by amenk** [comment] 2016-05-23 07:39
[yes, offtopic] Gajim seems to be sending <no-permanent-store xmlns="urn:xmpp:hints" /> - any clue how that hint can be removed?

**Comment by iNPUTmice** [comment] 2016-05-23 07:54
5320144d09002381a9c3ef8ecba34a3c0b301d47 adds the store hint. Not sure if this fixes OPs issue though. (This would require that the sending client in OPs case is gajim)

**Comment by mapama** [comment] 2016-05-23 07:57
> ```
> Go offline in Gajim
> Write in Conversations (Android) with OMEMO
> Go online in Gajim
> Open history in Gajim -> Message is there
> ```
> 
> Yes, that is not the problem. In this case the OMEMO-message is stored as offline message. As described above the problem occurs if another client is online while gajim is offline. In that case the OMEMO-message is not stored as offline message. But it should be stored via MAM, as it is the case for Non-OMEMO-messages.

**Comment by amenk** [comment] 2016-05-23 08:00
I am online also in a second client ...

**Comment by amenk** [comment] 2016-05-23 08:03
Thanks for the patch @iNPUTmice - It does not seem to fix the Problem with Gajim - I will have a look at the messages exchanged...

**Comment by amenk** [comment] 2016-05-23 08:18
I think the <store> hint has to be outside of the `</encrypted>` block? See my comparison between what conversations and what gajim sends ...
![selection_125](https://cloud.githubusercontent.com/assets/1087128/15464451/b8a79b72-20cf-11e6-8608-3a171c8ff4be.png)

**Comment by iNPUTmice** [comment] 2016-05-23 08:37
272187ce60df66384ea93bf1db97ed08257cf936

**Comment by amenk** [comment] 2016-05-23 08:51
Seems to work! Thank you so much!

**Comment by mapama** [comment] 2016-05-23 08:55
> I am online also in a second client ...

Strange, in that case the messages don't appear in my chat history in gajim. What could be the problem?

**Comment by amenk** [comment] 2016-05-23 08:56
Are you sending from Gajim? Does it work when sending i.e. from Conversations? Then the above patch is for you :D

**Comment by mapama** [comment] 2016-05-23 09:12
I tried the patch. But it doesn't help. I am sending from conversations. The recipient is online with conversations and offline with gajim. Going online with gajim, the message is missing in the chat history.

**Comment by iNPUTmice** [comment] 2016-05-23 09:15
@mapama What's the chat history? The history in the current chat window or the 'History Manager'?

**Comment by mapama** [comment] 2016-05-23 09:25
@iNPUTmice Not the current window. That one I get with Ctrl-H.

**Comment by lovetox** [comment] 2016-05-23 10:00
i can reproduce this now, with the patch from @iNPUTmice my outgoing xml from Gajim looks like this

```
<!-- Out 23.05.2016 11:51:18 -->
<message xmlns="jabber:client" to="xxx@jabber.at" type="chat" id="189">
<active xmlns="http://jabber.org/protocol/chatstates" />
<thread>xxxxxxxxxx</thread>
<encrypted xmlns="eu.siacs.conversations.axolotl">
   <header sid="675111788">
        <key rid="1830888488">xxxxx</key>
        <key rid="679408871">xxxxxx</key>
        <iv>xxxx</iv>
   </header>
    <payload>xxxxxx</payload>
</encrypted>
<store xmlns="urn:xmpp:hints" />
</message>

but when i come online with a second Gajim Client, the Client doesnt get this Message from MAM (jabber.at)

but for me it doesnt matter if conversations sends the message or Gajim, the offline third (Gajim) Client never gets the message.

Even when both Gajim Clients are Offline, and the Conversations Chat Partner sends a message, only the Gajim Client that comes online first gets the message

**Comment by lovetox** [comment] 2016-05-23 10:18
hm seems like my MAM is not working at all gajim querys the server but gets no response at all

```
<iq xmlns="jabber:client" type="set" id="329">
<query xmlns="urn:xmpp:mam:0" queryid="328">
<x xmlns="jabber:x:data" type="submit">
<field var="FORM_TYPE" type="hidden">
<value>urn:xmpp:mam:0</value>
</field>
</x>
<set xmlns="http://jabber.org/protocol/rsm">
<max>30</max>
<after>1461862207990877</after>
</set>
</query>
</iq>
```

**Comment by mapama** [comment] 2016-05-23 15:31
I can confirm this. It seems that MAM is not working anymore in gajim. I don't understand these strange thing. Even with disabled OMEMO the messages are not stored by MAM.

**Comment by kalkin** [comment] 2016-05-24 17:40
If this is a Gajim issue, may be @yann-l can have a look at that?

**Comment by lovetox** [comment] 2016-05-24 18:23
it seems jabber.at has a problem with MAM right now they are working on it.

**Comment by mapama** [comment] 2016-05-31 12:56
@lovetox did you find out the problem with jabber.at?

**Comment by lovetox** [comment] 2016-05-31 14:01
@mapama they had a problem, but its fixed since a few days, does it still not work for you?

**Comment by lovetox** [comment] 2016-05-31 14:26
@mapama you are right still not working, but its not jabber.at fault, mam seems to work, the messages come through but the plugin seems to drop them, im looking into this now

**Comment by iNPUTmice** [comment] 2016-05-31 14:43
Are MAM messages for the history window even processed trough the normal message hooks?

**Comment by lovetox** [comment] 2016-05-31 14:48
no i dont think so, i tested this, and the message never runs to the MessageReiceivedEvent

There is anohter MamMessageReiceivedEvent maybe its that

**Comment by lovetox** [comment] 2016-05-31 14:57
yeah thats it, event is mam-message-reiceived

**Comment by lovetox** [comment] 2016-05-31 18:07
@mapama if its not to much work for you you could try my branch

https://github.com/lovetox/gajim-omemo/

i included:
Fingerprint UI (only shows you the fingerprints for now)
You get better notification when OMEMO is disabled or someone writes you unencrypted
MAM Messages should work now

if everything works, i plan to make a pull request

**Comment by mapama** [comment] 2016-06-01 08:29
Thank you @lovetox MAM is now partially working. The received messages are shown in the history now but not my own carbon copied messages I wrote with conversations. Where do I find the Fingerprint UI?

Thanks a lot for your effort.

**Comment by lovetox** [comment] 2016-06-01 14:55
hi i will look into it today or tomorrow, could well be that i missed something

you find it under Plugins -> Omemo -> Configuration
select the account, then switch to the fingerprint tab

remember though the buttons "trust" and "untrust" do nothing, every fingerprint is trusted at the moment, even when the UI shows it as false.

**Comment by lovetox** [comment] 2016-06-01 15:33
seems like an encryption issue, i get the messages but cant decrypt them

@iNPUTmice 
i get a NoSessionException from the axolotl library.
but only if i get carbon copied MAM Messages.

normal carbon copies without MAM work.

do you have an idea whats maybe missing?

**Comment by lovetox** [comment] 2016-06-01 17:09
hm i think its the MAM Catchup that doesnt work or isnt even implemented.
this could take while

**Comment by lovetox** [comment] 2016-06-01 22:20
i believe i fixed it
https://github.com/lovetox/gajim-omemo/commit/7a7c5c76cb7cf4fce18b41ce428e8612961f34c6

please try it
@mapama

**Comment by mapama** [comment] 2016-06-02 08:50
Thank you so much @lovetox 
It seems to work exactly as it should.

**Comment by lovetox** [comment] 2016-06-13 11:18
MAM patch is now merged.

**Closed as completed by lovetox** 2016-06-13 11:18 UTC
