### ISSUE TITLE
protobuf 3.0.0b2.post2 AttributeError

### ISSUE THREAD

**Issue by purew** [kalkin/gajim-omemo#55] opened 2016-04-24 14:48 UTC
I kept getting the message "Please install axolotl" even though python-axolotl was install systemwide (/usr/local/lib), in local virtualenv, both for python2 and python3. 

Turns out something else is amiss. I changed the log-message above into the full traceback by changing https://github.com/omemo/gajim-omemo/blob/master/__init__.py#L45 into `log.exception("crash")`. 

See the following traceback, axolotl is obviously loaded but it seems like gajim hooks into the module-loading code and it goes back and fourth for a while before hitting an undefined `_message`.

> Traceback (most recent call last):
>   File "/home/anders/.local/share/gajim/plugins/omemo/**init**.py", line 42, in <module>
>     from omemo.state import OmemoState
>   File "/usr/share/gajim/src/common/demandimport.py", line 114, in _demandimport
>     mod = _origimport(name, globals, locals)
>   File "/home/anders/.local/share/gajim/plugins/omemo/omemo/state.py", line 29, in <module>
>     from axolotl.protocol.prekeywhispermessage import PreKeyWhisperMessage
>   File "/usr/share/gajim/src/common/demandimport.py", line 114, in _demandimport
>     mod = _origimport(name, globals, locals)
>   File "/usr/local/lib/python2.7/dist-packages/axolotl/protocol/prekeywhispermessage.py", line 9, in <module>
>     from .whispermessage import WhisperMessage
>   File "/usr/share/gajim/src/common/demandimport.py", line 112, in _demandimport
>     return _origimport(name, globals, locals, fromlist, level)
>   File "/usr/local/lib/python2.7/dist-packages/axolotl/protocol/whispermessage.py", line 9, in <module>
>     from . import whisperprotos
>   File "/usr/share/gajim/src/common/demandimport.py", line 112, in _demandimport
>     return _origimport(name, globals, locals, fromlist, level)
>   File "/usr/local/lib/python2.7/dist-packages/axolotl/protocol/whisperprotos.py", line 13, in <module>
>     _sym_db = _symbol_database.Default()
>   File "/usr/share/gajim/src/common/demandimport.py", line 86, in __getattribute__
>     self._load()
>   File "/usr/share/gajim/src/common/demandimport.py", line 58, in _load
>     mod = _origimport(head, globals, locals)
>   File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 180, in <module>
>     _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
>   File "/usr/share/gajim/src/common/demandimport.py", line 86, in __getattribute__
>     self._load()
>   File "/usr/share/gajim/src/common/demandimport.py", line 58, in _load
>     mod = _origimport(head, globals, locals)
>   File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor_pool.py", line 65, in <module>
>     _USE_C_DESCRIPTORS = descriptor._USE_C_DESCRIPTORS
>   File "/usr/share/gajim/src/common/demandimport.py", line 86, in __getattribute__
>     self._load()
>   File "/usr/share/gajim/src/common/demandimport.py", line 58, in _load
>     mod = _origimport(head, globals, locals)
>   File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 47, in <module>
>     _USE_C_DESCRIPTORS = getattr(_message, '_USE_C_DESCRIPTORS', False)
>   File "/usr/share/gajim/src/common/demandimport.py", line 86, in __getattribute__
>     self._load()
>   File "/usr/share/gajim/src/common/demandimport.py", line 58, in _load
>     mod = _origimport(head, globals, locals)
> ImportError: No module named _message

Running Ubuntu 14.04, gajim 0.16.5.

```
~ python --version
Python 2.7.6
```

```
pip list | grep axolotl
python-axolotl (0.1.34)
python-axolotl-curve25519 (0.1)

```

**Comment by kalkin** [comment] 2016-04-25 05:44
Downgrade to `protobuf==3.0.0b2` this is a known error, I'm working on it.

**Comment by djmaze** [comment] 2016-05-06 15:23
Downgrading to `protobuf==3.0.0b2` doesn't solve the problem for me. Same error as @PureW. Arch Linux, gajim 0.16.5.

``` bash
$ python2 --version                                                        
Python 2.7.11
$ pip2 list | egrep "axolotl|protobuf"
protobuf (3.0.0b2)
python-axolotl (0.1.35)
python-axolotl-curve25519 (0.1)
```

**Comment by kalkin** [comment] 2016-05-06 15:36
I have to correct my self: downgrade to protobuf 2.7 or upgrade to Gajim 0.16.6

**Comment by djmaze** [comment] 2016-05-06 15:53
Ok, so as 0.16.6 is not yet out, the critical change is probably [this one](https://trac.gajim.org/changeset/36cecfcc49f3adc70c9783df656594125beb72f6/)? At least the plugin seems to be correctly working after manually applying the change.

**Comment by kalkin** [comment] 2016-05-06 16:02
@djmaze Exactly!

**Comment by asterismo** [comment] 2016-05-10 16:05
How do i downgrade that lib? is that safe?

**Comment by kalkin** [comment] 2016-05-10 23:20
@asterismo should be safe. 

```
 pip install protobuf==2.6.1, python-axolotl==0.1.35 
```

**Comment by asterismo** [comment] 2016-05-12 21:49
Nope, this is really frustrating. I have gajim-nightly installed, and installed those versions of protobuf and axolotl you mentioned. Now i just upgraded all libs and i'll sit and wait until this eventually work with latest versions of everything.

**Comment by benediktg** [comment] 2016-07-09 12:35
@asterismo E. g. openSUSE Leap and Tumbleweed have pip3 installed by default so that you at first have to

``` bash
sudo zypper install python-pip  # the python2 version of pip
# and then
sudo pip2 install protobuf==2.6.1 python-axolotl
```

There has to be no comma between the `protobuf==2.6.1` and the `python-axolotl`. In adition to that it's not necessary to put in `==0.1.35` since it's the most current version anyway.

**Comment by lovetox** [comment] 2016-07-21 20:38
@asterismo did you try this
`pip install protobuf==2.6.1 python-axolotl`

if it is still not working i would need some log output

are you seeing the plugin in the plugin manager ? (as a installed plugin)

start with
`-l gajim.plugin_system.omemo=DEBUG`

if that yields nothing start with 

`-l gajim=DEBUG`

and search for a error regarding to `google`

**Comment by lovetox** [comment] 2016-11-28 16:52
i close this, solution to the problem is in the wiki [here](https://dev.gajim.org/gajim/gajim-plugins/wikis/OmemoGajimPlugin)

**Closed as completed by lovetox** 2016-11-28 16:52 UTC
Labels: bug
