### ISSUE TITLE
Can not subscribe to pubsub presence-subscription-required 

### ISSUE THREAD

**Issue by tristan-k** [kalkin/gajim-omemo#8] opened 2015-12-29 17:29 UTC
I'm pushing the button "Get Device Keys" but the XML console is telling me something about an auth error.  

```
<!-- Out Di 29 Dez 2015 19:24:45 IST -->
<iq xmlns="jabber:client" to="tristank@jabber.tristank.de" type="get" id="63705162-abc3-41d8-98f7-eaa9151aff0b">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<items node="eu.siacs.conversations.axolotl.bundles:355207054" />
</pubsub>
</iq>

<!-- In Di 29 Dez 2015 19:24:45 IST -->
<iq id='63705162-abc3-41d8-98f7-eaa9151aff0b' type='error' to='franziskaw@jabber.tristank.de/Gajim' from='tristank@jabber.tristank.de'>
<error type='auth'>
<not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
<presence-subscription-required xmlns='http://jabber.org/protocol/pubsub#errors'/>
</error>
</iq>
<r xmlns='urn:xmpp:sm:2'/>

<!-- Out Di 29 Dez 2015 19:24:45 IST -->
<a xmlns="urn:xmpp:sm:2" h="170" />
```

**Comment by kalkin** [comment] 2015-12-30 12:04
Thank you for your report. 

It looks like you can not subscribe to the pep of franziskaw because you are missing presence subscription. I need to hide the button if you do not have the subscription. 

In the future please anonymize private data like jids of other people. :wink:

**Comment by iNPUTmice** [comment] 2015-12-30 17:17
In case of a missing presence subscription we shouldn't receive the device list thus we usually don't display the missing keys button. I guess in this case the presence subscription was lost during the life time of the gajim session. Imho this is an edge case that can probably be covered by the normal error handling that should be in place anyway to check if the bundle fetch was unsuccessful.

**Comment by strb** [comment] 2015-12-31 15:00
I have seen a similar issue which I've ascribed to a server bug (but this is not confirmed). This was in Conversations, but we observed very similar behavior. The client would still receive the devicelist update, but couldn't fetch the bundle (same `<presence-subscription-required/>` error). They still received devicelist updates even after this error was seen, so it definitely wasn't a presence subscription lifecyle/"timing" issue. I don't have any logs or anything, all I know is that we saw this on an ejabberd server. 

Having the  contact remove and re-add the permission for presence subscription (and re-starting Conversations to trigger a re-fetch of the bundle) fixed the problem in this case, which further points to some bug with ejabberd's presence handling and/or PEP code.

**Comment by kalkin** [comment] 2016-01-07 23:32
This should be fixed in ce63cc8e583dc6099b45d8cb44ee95c9394b6bd2 
Now the ui is only created if the recipient supports OMEMO.

**Comment by kalkin** [comment] 2016-01-11 13:45
@tristan-k Which Jabber Server are you using ejabberd? If so which exact version on which exact os?

**Comment by kalkin** [comment] 2016-01-11 13:47
@tristan-k also did updating help? It shouldn't have, my [note here](https://github.com/kalkin/gajim-omemo/issues/8#issuecomment-169840288) was accidental.

**Comment by strb** [comment] 2016-01-11 14:07
The problem I described earlier was on ejabberd-15.07.

**Comment by kalkin** [comment] 2016-01-11 16:54
@strb So is this the old ejabberd version, which also has other issues with PEP?

**Comment by lovetox** [comment] 2016-06-14 13:58
@strb @tristan-k 

is this still an issue?

**Comment by lovetox** [comment] 2016-06-20 20:43
closing until there is new information

**Closed as completed by lovetox** 2016-06-20 20:43 UTC
Labels: enhancement
