### ISSUE TITLE
fingerprint needs to be accepted manually

### ISSUE THREAD

**Issue by schiessle** [kalkin/gajim-omemo#90] opened 2016-07-26 08:04 UTC
It happens to me multiple time that I need to accept the fingerprint of a chat partner manually before my messages are send to him. Even more problematic, as long I didn't accept it I don't receive and message from him and he doesn't know. So it can happen that people write to me and wonder why I don't response, but actually I never received a message from them.

I assume that the right behavior would be to either accept the fingerprint manually or at least get a message like "someone wrote to you, please check the fingerprint". But to make it easy for non-technical people I would probably prefer the first solution. I think Conversations works similar, at least I never had to accept a fingerprint there.

**Comment by iNPUTmice** [comment] 2016-07-26 09:00
>  Even more problematic, as long I didn't accept it I don't receive and message from him and he doesn't know.

I can't reproduce this behaviour. For me messages from undecided devices show just fine.

**Comment by lovetox** [comment] 2016-07-26 09:02
> It happens to me multiple time that I need to accept the fingerprint of a chat partner manually before my messages are send to him

this is intended. why would you send messages to a device you didnt trust before?

you can receive messages from UNDECIDED fingerprints.
i just tested this again. if i have contact with only undecided fingerprints (means i cant send messages to him) he can send messages to me without a problem.

A Message not reaching you can have a multitude of reasons, for example maybe your chatpartner didnt trust your fingerprint, or you were offline and have a server without MAM and multiple devices.

to help you you should try to narrow it down to a specific scenario.

also which version of the plugin are you using?
if you suspect problems, you can start gajim with -l gajim.plugin_system.omemo
that will log all omemo related debug output to a file, you then could look for dropped messages.

messages from contacts always reach you (if we dont suspect a bigger problem with server/gajim)
they just cant be decrypted, and that would show in the logs, and we could then see why they cant be decrypted

**Comment by schiessle** [comment] 2016-07-26 09:22
The problem happened with version 0.7.0 now I updated to 0.7.5. Is there a way to clear all know fingerprint so that I can try it again. Looked at .config/gajim/pluginsconfig/ but couldn't find any list of the know fingerprints there.

**Comment by lovetox** [comment] 2016-07-26 09:33
the fingerprints are in a sqlite db
its called omemo_yourserver.db
you can look at it with a db programm that can read sqlite

there are 2 tables: identities and sessions
if you want to reset everything for one contact
delete every row with the JID of the contact from the `sessions` and `identities` table.
restart gajim.

beware: do not delete the first row out of `identities` or you will get new fingerprint for your device which has to be accepted by your contacts again.

if you just want to test and dont care about new fingerprints generated for your device, you could just delete the whole db, should be created at start of gajim new.

**Comment by lovetox** [comment] 2016-07-29 12:36
@schiessle so is there still an issue? otherwise i will close this

**Closed as completed** 2016-07-29 13:18 UTC
