### ISSUE TITLE
OMEMO enabled for resource that doesn't support it

### ISSUE THREAD

**Issue by jhass** [kalkin/gajim-omemo#71] opened 2016-06-28 16:36 UTC
I have a contact online with two clients, one that does support OMEMO (Conversations) and one that doesn't (Pidgin). The contacts server does not support message carbons. I installed the latest version of the plugin from git with Gajim 0.16.5.

I cannot find a way to send messages to the pidgin resource, since starting a chat wit the pidgin resource enables OMEMO anyway and I can't find a way to disable OMEMO for a chat, neither one with a specific resource nor one with the contact in general.

**Comment by jhass** [comment] 2016-06-28 16:39
Okay it looks like it's due to the "Make message windows compact" setting. I think in that mode the little shield button, that's already a button UI wise so you do can click on it, just nothing happens, should either toggle the OMEMO state directly or have a little options popup where you can toggle it etc. As it stands the current UI in the "Make message windows compact" mode is highly confusing and I would argue dysfunctional, since it should retain a way to those options.

That it autoenables at all for a resource chat that doesn't support I would still consider a separate bug though.

**Comment by lovetox** [comment] 2016-06-28 17:21
the shild button does nothing, its just a way to know the current encryption state.
the button is btw not part of the plugin. we can just set its state

do you see the omemo checkbox and the fingerprint button?

compact window, means no buttons. you could argue that you cant use all the other functions in that state as well, so why should you be able to control omemo?

omemo doesnt know with what client your contact is online and if he supports omemo or not.
omemo checks if your contact has published device ids.

if your contact has published a device id that means he has at least one device that supports omemo.

if he has multiple devices, for example pidgin and conversations, its impossible for the plugin to guess on which device he is currently sitting.

imagine he has a laptop and a mobile, both online, he sits in front of the pc, his mobile is right on the table next to him.

how should the plugin know, if the next message should go encrypted to his mobile or unencrypted to his pc?

**Comment by jhass** [comment] 2016-06-28 17:52
When my contact is online with multiple resources, I can right click on its roster entry and pick a specific resource to talk to under "Start Chat".

When I right click on my contacts roster item and choose "Information", the resulting window has a "Client" entry under the "General" tab, so some information seems to be available. One could at least blacklist stuff known to have no implementation.

OTR has detection whether the remote resource supports OTR, at least it can automatically start an OTR session in that case somehow. Is all OMEMO has here really whether a device keys are published? And are device keys really not associated with a resource? That surprises me a bit, I would have thought listing the resources a device key is available for would be an obvious design choice.

**Comment by klemens** [comment] 2016-06-28 22:01
> compact window, means no buttons. you could argue that you cant use all the other functions in that state as well, so why should you be able to control omemo?

Most (if not all) functionality is available through the context menu in this case, including eg. the OTR settings. This is how OTR adds its context menu entry: https://github.com/python-otr/gajim-otr/blob/0613803545b7972ab57059cfb312d62a5a9dbbf1/src/gotr/otrmodule.py#L343-L349

Edit: OTR also hijacks the shield button with its own menu (in the same file a few lines above).

**Comment by jhass** [comment] 2016-06-28 22:02
Yes, I was looking through all context menus I could find.

**Comment by lovetox** [comment] 2016-06-29 13:54
with message carbons activated every message reaches all clients, it doesnt matter if you start a chat with a specific resource. Also your problem doesnt exist if you know beforehand with what device you want to talk, instead of clicking "start chat with" you could just click the omemo deaktivate button and get the same thing.

The problem is when you dont know on which device your friend is at the moment, what do you do then?

to make it short, OMEMO is a Multiple Device encryption, it was designed so that you have multiple devices that all get the same encrypted messages.

OTR doesnt has a detection at all. What OTR does, it sends a message with (?OTRxxxxx) to the contact, which gets copied to all clients via carbons, one can send back that it supports OTR and then a single encryption between these two devides start, which the other device can not listen to.

if a device doesnt support OTR, it will receive something like this and show it

```
?OTR:AAIDAQAAAAEAAAABAAAAwLw7qlHXmYaiLIq4nkA/DmsrSQ7awm1ivew66UjgIt2Ver8vhNRT1BQjGzs54WgCcf74/kZGvK9uhtUddGnyTMscCA5vNACa2jLNGqhosv5VPsY7lSrh2zluihjxk8nVzQkNq7qm4zT1/igjvTJu8dp9YnvcVn6yKRFM4ZnliPq6mIGIsMzaTDSDUBoJw9rH72rfFfW1435FDlnVk3n+BXaKUtrzLfWQzp+ANZ+xzWlcjhZDfuU0qiwBo+x5k2VHugAAAAAAAAABAAAABWwDSC4mg58AyTWxLTUnVglvA4R8oZ4EL70AAAAU0bbaXE7AfYf8OFHZRc69p/bfpRg=
```

so if you ask me thats not exactly optimal
Also you can see that the buttons for OTR are there for all your contacts even when they dont support OTR, if you click start encryption your contact will see the text above, really nice.

you are right there is a context menu, i will try to add the omemo menu to it.
not to the shield button though, as hijacking it by multiple plugins will lead to problems i dont want to deal with.

Also i strongly advice against using OTR and OMEMO with the same contacts. The OTR Plugin maybe set the Shield button to whatever value, and it doesnt reflect the correct state for OMEMO anymore.

It will not be possible to switch between encryptions flawlessly.

every encryption has a use case, it can work outside of the use case, but you will have issues.

OTR: single client to single client encryption, no sync across devices, no message archive
OMEMO: multiple devices, sync across all devices and message archive

OTR is old and a dying encryption at least in this version. OMEMO will not be tailored around it so both is flawlessly possible.

**Comment by jhass** [comment] 2016-07-18 11:04
> the shild button does nothing, its just a way to know the current encryption state.
> the button is btw not part of the plugin. we can just set its state

The OTR plugin adds a menu to it btw. It also hides it if OTR is disabled but OMEMO is enabled. Maybe there can be some collaboration between the two plugins here, possibly via requiring a third plugin that provides a unified management API to it? If that sounds like a good idea to anybody, getting Yann as the most recently active contributor to the OTR plugin (http://hg.gajim.org/gajim-plugins/log/f9ae5b16620b/gotr/otrmodule.py) into this discussion would probably be a good idea.

**Comment by lovetox** [comment] 2016-07-18 13:43
there is already a PR for a additional context menu, not at the shield button though. so you will have your possibility to activate omemo even in reduced window mode.
2 places in a chatwindow where you can activate omemo is enough, no need for a third place.

omemo is not OTR, i know you activate and deactivate and authenticate OTR constantly, with omemo you should only have to activate it once, maybe verify a key, but thats it for a loooong time. you should probably not think about it again for years (maybe someone changes his mobile).

the rest is out of scope of this plugin.
yeah it would be nice to have a API, but if you are not writing it, its probably not going to happen :)

**Comment by lovetox** [comment] 2016-07-18 14:46
the new context menu is now merged, just download the newest HEAD, or wait one or two weeks for the next release version. hope it suits you.

thanks to @klemens !

**Closed as completed by lovetox** 2016-07-18 14:46 UTC
