### ISSUE TITLE
messages don't appear when using different clients

### ISSUE THREAD

**Issue by silberzwiebel** [kalkin/gajim-omemo#51] opened 2016-04-01 09:31 UTC
Hi,

I'm using Conversations on Android and gajim + OMEMO plugin on two PCs (Fedora 23) with a self-hosted prosody server.
OMEMO encryption is enabled on all clients.
At least with one contact, however, the OMEMO encrypted messages only appear on Conversations. I can send messages with both clients and apparently they are successfully sent and received by the contact. But if he responds, the message only appears in Conversations.
I had similar problems with different contacts and the impression that gajim+omemo just not catches all messages.
[Here is some output from `gajim -v'](https://gist.github.com/silberzwiebel/63c8c7e552670a265d3f156602fe385d), I think it is too much, but hope you can figure it out, nevertheless. During that time messages were sent but didn't appear in the chat window of gajim.

Thanks for fixing,
silberzwiebel

**Comment by silberzwiebel** [comment] 2016-04-05 09:35
Tested this again with the plugin version from this repo (before I used the 0.4 version available from within gajim). I also removed the omemo_....db file in `~/.local/share/gajim/`because I think this is a problem of missing keys and this could help to fetch the missing keys. However, messages still don't appear. [Here is a part of the output of `gajim -l gajim.plugin_system.omemo=DEBUG -v` that contains a not-appearing message.](https://gist.github.com/silberzwiebel/b7b85fbc4dfbd3c6b0ab0a203571bc4d)

One message in this log might explain the problem:
    `OMEMO message does not contain our device key`

If I  understand this correct, then the problem would be on the other side, i.e., here Conversations (that my chat-partner is using) does not have / ask for the key of my gajim device. Either way, at least an error message in the gajim chat window would be good such as: `Error: Received an encrypted message but couldn't decrypt it. Please try ....`

**Comment by lovetox** [comment] 2016-04-20 21:52
@iNPUTmice could that be a bug with conversations?

could you check if your chat partner in conversations has a fingerprint activated for each of your devices?

**Comment by lovetox** [comment] 2016-04-20 23:41
so i set up a windows pc with gajim, a linux with gajim, both logged into the same account
talking both to conversations.

works alright for now in every direction.

did your friend on conversations ever delete a fingerprint?
does conversation has both fingerprints under contact details?
are both of your other clients use the version from github?
are you sure you are on version 0.16.5 of gajim?

**Comment by silberzwiebel** [comment] 2016-04-22 11:26
My chat partner has 4 OMEMO fingerprints in the contact details of my XMPP-account, although I'm using only 3 clients: 2 x gajim (desktop and laptop) and 1 x Conversations.
In my own contact details of my Conversations, I also have 4 OMEMO fingerprints (the one from Conversations and three more).
I clicked the button "Clear Device Keys" randomly on gajim (it is not clear to me what it is supposed to do), so maybe this is the reason I got one fingerprint too much? And, as I wrote earlier, I also deleted the omemo_....db file in ~/.local/share/gajim/.

Both of my gajim clients are using the github version, and both gajims are on version 0.16.5 (from the the fedora 23 repos).

I have this issue only with one contact at the moment, with other contacts it works.

**Comment by silberzwiebel** [comment] 2016-05-10 10:16
I just had this issue (or at least a related one) with a different contact.
Chatting with gajim at a laptop and at the same time with conversations. Messages came through most of the time but stopped to appear in conversations now for some time.
Since my server was under heavy network load, my best guess is now the following: Conversations was offline and the messages I send and received were not encrypted with the ocnversations OMEMO key and thus not appeared there (if this is at all how OMEMO works, I might be totally wrong ...)

**Comment by kalkin** [comment] 2016-05-10 11:30
@cippaciong Does this look similar to what you are suffering from?

**Comment by cippaciong** [comment] 2016-05-10 11:51
Definitely, my problem is very similar to what @silberzwiebel described in the first message.

The scenario looks like this:
1. **Me** with 3 clients: Conversations, Gajim+OMEMO on desktop, Gajim+OMEMO on netbook (both running Archlinux and OMEMO plugin installed from AUR)
2. **Interlocutor A**: Conversations
3. **Interlocutor B**: Conversations

All my OMEMO fingerprints are trusted by my interlocutors and I trust theirs as well as mine from other clients.
- When I am using Conversations or Gajim on desktop I can send/receive messages to/from any interlocutor and I receive my messages sent from Conversations as well.
- When I am using Gajim from my netbook messaging works fine except that with one of the interlocutors (say B).
  I can write to her using Gajim but I don't receive either her replies or my replies sent from Conversations. It should be noted though that I can see status messages in Gajim (composing, paying attention to the conversation, etc.) and if I have a new message notification on Conversations and I focus the Gajim chat window  the notification disappears as if the message has been read.

**Comment by silberzwiebel** [comment] 2016-05-25 14:53
I'm experiencing this issue right now with different contacts, messages are not appearing at the Conversations side right now. Since some of them don't use an OMEMO capable client, it seems not to be an OMEMO problem. It might actually be also a server problem, I'm running prosody nightly. Nothing remarkable in the logs, though.
Any tips to get closer to this bug?

**Comment by lovetox** [comment] 2016-05-31 18:18
@cippaciong did you look into the gajim logs if there are any error messages or weird stuff?

you can test this one other way, just write from one client to another where it works
and watch from the client which doesnt get the replies, gajim has a xml console.
if you receive the XML we can rule out some server issue

**Comment by cippaciong** [comment] 2016-05-31 19:52
@lovetox I can see Gajim receives the message from the XML console but nothing is displayed in the chat window. The message is probably discarded for some reason.

**Comment by lovetox** [comment] 2016-05-31 19:55
@cippaciong 

could you start gajim with "-l gajim.plugin_system.omemo=DEBUG"

then reproduce the bug and post whats in the log

**Comment by cippaciong** [comment] 2016-06-02 09:38
@lovetox 

```
02/06/2016 11:30:48 (E) gajim.plugin_system.omemo No Session found No valid sessionsOver 2000 messages into the future!
02/06/2016 11:30:48 (E) gajim.plugin_system.omemo sender_jid →  cippaciong@cakeboss.tk sid =>1952001488
```

But I'd say that the session is actually stored in the db:

```
sqlite> select recipient_id,device_id from sessions where device_id=1952001488;
cippaciong@cakeboss.tk|1952001488
```

**Comment by lovetox** [comment] 2016-06-02 13:26
could you use the omemo from my repo and see if it fixes your problem

https://github.com/lovetox/gajim-omemo

**Comment by lovetox** [comment] 2016-06-13 11:26
@cippaciong @silberzwiebel 

is this solved or do you still see this problem?
(with the current head)

**Comment by cippaciong** [comment] 2016-06-13 18:04
It's solved for me :smiley:

**Comment by silberzwiebel** [comment] 2016-06-14 12:54
I've used the latest version from this git repo, not your fork @lovetox but unfortunately it does not work for me. I can rule out a server issue, because the message appears in the XML-Console but it is not displayed (I can see it in Conversations, though):

```
<!-- In Di 14 Jun 2016 14:45:18 CEST -->
<message id='d9c5d6eb-dc68-4207-a604-119bd52b6c30' type='chat' to='thomas@kartoffelsalat.ddns.net' from='laura@kartoffelsalat.ddns.net/mobile'>
<encrypted xmlns='eu.siacs.conversations.axolotl'>
<header sid='1802001548'>
<key rid='1059429025'>MwohBTLac/nXD5hYTneOBNGDyn6eocoLwCcy8QkwARn7oPBFEAAYACIg2ArhnVwruTZ5ufqrhvAu
VuLN0nc2j2rlc2Ayxw6aHzMGrSC2xFsWWQ==
</key>
<key rid='1285421494'>MwohBfhcWVDwVtqDts5m8uKykF8WEruxbBDJXPK71JhAOmpoECQYASIgnTZw9F3j7Zcl4e61r4df
PrsYi1yU0ojNc/0kSJ7wJaSWT8ZuspwHzA==
</key>
<iv>zdqJsUsnuoFpc7dxkDi+dw==
</iv>
</header>
<payload>rvIlMqYYcbAZJJLjs7qPh8ME8r/89pYHIUpd9Q==
</payload>
</encrypted>
<markable xmlns='urn:xmpp:chat-markers:0'/>
<store xmlns='urn:xmpp:hints'/>
</message>

<!-- Out Di 14 Jun 2016 14:45:18 CEST -->
<a xmlns="urn:xmpp:sm:2" h="130" />

<!-- In Di 14 Jun 2016 14:45:19 CEST -->
<message type='chat' to='thomas@kartoffelsalat.ddns.net/Gajim' from='thomas@kartoffelsalat.ddns.net'>
<sent xmlns='urn:xmpp:carbons:2'>
<forwarded xmlns='urn:xmpp:forward:0'>
<message xmlns='jabber:client' type='chat' to='laura@kartoffelsalat.ddns.net/mobile' from='thomas@kartoffelsalat.ddns.net/mobile'>
<displayed id='d9c5d6eb-dc68-4207-a604-119bd52b6c30' xmlns='urn:xmpp:chat-markers:0'/>
<store xmlns='urn:xmpp:hints'/>
</message>
</forwarded>
</sent>
</message>

<!-- In Di 14 Jun 2016 14:45:20 CEST -->
<r xmlns='urn:xmpp:sm:2'/>
```

I repeat my idea that it would be at useful to display at least a message like "Error: Received encrypted message but could not decrypt it."
At the moment it also seems to not work in neither way: When I send a message from gajim, it only appears at my Conversations but not at the Conversations from my contact.
Could it be actually a bug in the Message Carbons part of gajim and / or prosody?

**Comment by silberzwiebel** [comment] 2016-06-14 12:57
Ok, this is a weird bug. The next messages happened to appear in gajim just fine. This is from the XML-Console for these messages, maybe it helps:

```

<!-- In Di 14 Jun 2016 14:55:39 CEST -->
<message type='chat' to='thomas@kartoffelsalat.ddns.net' from='laura@kartoffelsalat.ddns.net/mobile'>
<active xmlns='http://jabber.org/protocol/chatstates'/>
<no-store xmlns='urn:xmpp:hints'/>
<no-storage xmlns='urn:xmpp:hints'/>
</message>

<!-- In Di 14 Jun 2016 14:55:39 CEST -->
<message id='26bcf5db-03d2-467e-acf8-8ea67696027b' type='chat' to='thomas@kartoffelsalat.ddns.net' from='laura@kartoffelsalat.ddns.net/mobile'>
<encrypted xmlns='eu.siacs.conversations.axolotl'>
<header sid='1802001548'>
<key rid='1059429025'>MwohBeSabmBtUWeMTc+kiZC/6PjGPk2yEWJW78zJhcvQv3FbEAIYAiIgfQw9w3LbW6wApPYTJMcg
QBoYr70BjH4192rwNmpmPfSpeWRUZucOpw==
</key>
<key rid='1285421494'>MwohBfhcWVDwVtqDts5m8uKykF8WEruxbBDJXPK71JhAOmpoECkYASIgcxwQHqIRdETpRxPMP/lg
OckJPbzVOefDH322NTXkXHPKzJCAE+c76A==
</key>
<key rid='321776365'>MwohBaP5aXIVGCkTu0U46Nqk/1YqINaiDJ7oy6oyXISgAZ9bEAIYAiIgNGlAfpX0mdAiQ1XNE2Zb
F+ouIjK5dCMh2kZ6UHBilONQwTMg7UU0lA==
</key>
<iv>YqCiMqbH/3xCPvIeX5/ZSA==
</iv>
</header>
<payload>CyKFNdS/pnzEejJkovgML82ChSN9JcFCNiOCRrUq
</payload>
</encrypted>
<markable xmlns='urn:xmpp:chat-markers:0'/>
<store xmlns='urn:xmpp:hints'/>
</message>

<!-- In Di 14 Jun 2016 14:55:40 CEST -->
<message type='chat' to='thomas@kartoffelsalat.ddns.net/Gajim' from='thomas@kartoffelsalat.ddns.net'>
<sent xmlns='urn:xmpp:carbons:2'>
<forwarded xmlns='urn:xmpp:forward:0'>
<message xmlns='jabber:client' type='chat' to='laura@kartoffelsalat.ddns.net/mobile' from='thomas@kartoffelsalat.ddns.net/mobile'>
<displayed id='26bcf5db-03d2-467e-acf8-8ea67696027b' xmlns='urn:xmpp:chat-markers:0'/>
<store xmlns='urn:xmpp:hints'/>
</message>
</forwarded>
</sent>
</message>
<r xmlns='urn:xmpp:sm:2'/>
```

**Comment by lovetox** [comment] 2016-06-14 13:37
there is a info displayed for every message that arrives, but you have to look at the log

start gajim with "-l gajim.plugin_system.omemo"

this should solve this mystery.

please before you try to reproduce this error, be sure that in gajim every fingerprint of your contact is trusted.

in the config dialog of the omemo plugin under the tab "Clear Devices", there is a list with published devices. make sure that all your devices are in there.

and last make sure that the fingerprint of your devices is trusted in the conversations client of your contact.

**Comment by silberzwiebel** [comment] 2016-06-20 13:37
It's hard to tell whether all my devices are in the list under "Clear Devices". There were three, which is fine (2 \* gajim, 1\* Conversations),  but then I clicked "Clear devices" (totally unsure what this is meant to do), and now there are only 2 left (which is fine considering that I only have 2 devices online at the moment).
Is there any possibility to set names for the different keys?

Next, I do not receive the new OMEMO key from at least one of my contacts, I know that she has a new device, but I still have only one single (old) fingerprint. So, I can't trust the new fingerprint and also do not send her encrypted messages.
But: She can send me encrypted messages that do not appear in the gajim UI. Here is one attempt:

```
20.06.2016 15:07:12 (D) gajim.plugin_system.omemo: xmpp-server => OMEMO msg received
20.06.2016 15:07:12 (D) gajim.plugin_system.omemo: ZSe2uoqPfoNLhInYo5sOMg==

20.06.2016 15:07:12 (D) gajim.plugin_system.omemo: hiwYUun6P6oiEDxqodbpI2Y=

20.06.2016 15:07:12 (D) gajim.plugin_system.omemo: MwohBWay0Lmqfh9DEa2kGWTVkx+XEL3qLWSOmQ0ijiKu4SwNEAYYASIgHotxRLz0IxeIQHTF/RAV
9LCqwzh9cVIr41jcmh4ESGjwAZc5V/G8zw==

20.06.2016 15:07:12 (D) gajim.plugin_system.omemo: Parsed OMEMO message:{'keys': {1059429025: '3\n!\x05f\xb2\xd0\xb9\xaa~\x1fC\x11\xad\xa4\x19d\xd5\x93\x1f\x97\x10\xbd\xea-d\x8e\x99\r"\x8e"\xae\xe1,\r\x10\x06\x18\x01" \x1e\x8bqD\xbc\xf4#\x17\x88@t\xc5\xfd\x10\x15\xf4\xb0\xaa\xc38}qR+\xe3X\xdc\x9a\x1e\x04Hh\xf0\x01\x979W\xf1\xbc\xcf'}, 'iv': "e'\xb6\xba\x8a\x8f~\x83K\x84\x89\xd8\xa3\x9b\x0e2", 'payload': '\x86,\x18R\xe9\xfa?\xaa"\x10<j\xa1\xd6\xe9#f', 'sid': 1208374790}
20.06.2016 15:07:12 (W) gajim.plugin_system.omemo: OMEMO message does not contain our device key
Logger gajim.plugin_system.omemo level set to 10
```

The key with the ID 1059429025, however, does appear in the list under "clear devices".
On the side of my contact, however, there is also only one OMEMO key, which is the one from my Conversations client. So, it is fine that I do not see those messages in gajim: But why does my contact does not get my new gajim key and why do I not get her new key?

**Comment by lovetox** [comment] 2016-06-20 14:07
so what Clear Devices does, is it overwrites the list with your published devices, that your contacts get.

but every device from you that is online adds itself to the list again instanstly.
only devices that are not online or broken cant do that. so thats a mechanism to get devices out of your published list that you dont use anymore.
So the Tab Clear Devices in Gajim just shows you what devices currently are published. if you use two and there are two device IDs, everything is ok.

to find out which client is what device ID, just send a message from gajim and look at the xml console. in the message stanza there is a line called "header" and there is a "sid" thats the sender device ID.

so from gajim side it looks ok.
question is now why your contact doesnt receive the publised device and key.
this can have multiple reasons.

first i would try to restart the conversations app, this would trigger your server to send out the device IDs again.

another reason could be that your contact deleted the fingerprint from that device, this can not be undone, your device is banned from his app.

to the problem why you do not receive her new device ID:
what server does the contact use?
what is the device? Gajim or Conversations
restarting the app could solve this again. contacts and yours.

just for info: at the current versions old fingerprints get not deleted, nor is it shown that they are old and inactive, so dont get confused if you have later 2 fingerprints in your window for a contact who uses currently only one device.
this will be changed soon

**Comment by silberzwiebel** [comment] 2016-06-25 18:18
While I tried to reproduce this, I found a [bug over at prosody side](https://prosody.im/issues/issue/673) that might be related to this and hopefully will also fix this issue. I've just updated my server and will report back...

**Comment by lovetox** [comment] 2016-06-25 18:46
this bug should not be related to your problems as it states that pep events are infact exchanged, you just have to login after adding someone.

that could be a problem if you look at the process flow after adding someone, but not with your old contacts

**Comment by nicorikken** [comment] 2016-07-11 18:55
Trying out this plugin, I also ended up in a disconnected state (2 accounts, both Gajim and Conversations for both). The suggested solution of 'Clear Devices' and restarting both clients did the job just fine. In Converstions, in my account details, I can see that I had 2 old keys registered, which are no longer in use (they remained offline after the restart).

**Comment by lovetox** [comment] 2016-07-16 10:08
so please use the new version 0.7 and see if you still have problems

**Comment by silberzwiebel** [comment] 2016-07-17 20:32
Okay, finally I have a "stable" test case to reproduce this bug (or at least one instance of it.)
I'm chatting with my contact only with Conversations (both f-droid version 1.13.5), my gajim with OMEMO plugin 0.7 (from this repo) is offline. When I start gajim I can send OMEMO encrypted messages that appear on my mobile and my contacts mobile. So far, so good.
However, I did not receive any message that was sent with Conversations when gajim was offline. The OMEMO debug output also does not mention any incoming message.
When I turn off Conversations and chat with gajim only, all sent messages sync with Conversation when I go with it online again.
All fingerprints / keys are known and trusted in all involved devices.

I keep thinking that (at least for this testcase) is not a encryption bug but a MAM or Message Carbons bug at gajims side. Gajim seems to not retrieve messages that were sent while being offline. It does work with a non-encrypted MUC, but I have similar problems with a non-encrypted 1-to-1 chat.
Do you know of any possibly related gajim issue?

**Comment by iNPUTmice** [comment] 2016-07-17 20:38
> Gajim seems to not retrieve messages that were sent while being offline.

Gajim does not use MAM to 'catch up' with message like Conversations does. Gajim doesn't have the concept of infinite per conversation history. Gajims support for MAM comes in form of a history browser at View / History.

**Comment by silberzwiebel** [comment] 2016-07-17 20:42
I cannot see the "lost" messages in the history window, though. They
should appear there, shouldn't they?

(As a sidenote, I found under the extended configuration a setting to
enable something similar as an "inifinite" converstations (setting keys
restore_lines and restore_days IIRC).)

**Comment by iNPUTmice** [comment] 2016-07-17 20:48
> (As a sidenote, I found under the extended configuration a setting to enable something similar as an "inifinite" converstations (setting keys restore_lines and restore_days IIRC).)

Gajim might not automatically issue a MAM request and instead restore the message from local history only.

> I cannot see the "lost" messages in the history window, though. They should appear there, shouldn't they? 

I'm not sure if MAM message retrieved for that archive view run through the same message hooks that are used to process OMEMO messages. That needs to be checked.

**Comment by lovetox** [comment] 2016-07-18 13:29
on start Gajim retrieves all MAM Messages since it was offline, these Messages also run through OMEMO, and you should see them in your history window (you dont get notifications for MAM)

it looks to me like your MAM is not working if you have the same problem with unencrypted Messages.
Please limit your testing to non-MUC Conversations.

i would try to make a case where you can test if MAM is working

**Comment by herndlm** [comment] 2016-07-28 14:08
Hi, I started using Conversations and was also using Gajim with the latest omemo plugin (0.7.5) and I had big problems after adding myself as a contact to test omemo with. I was not able to see my own messages sent from other devices (messages from Conversations were not appearing in Gajim and vice versa).
After deleting the plugin config and re-creating my account and plugin settings everything started to work again. Maybe this helps somebody. **Just don't add yourself for testing** :)
I don't really know why it broke but I also had problems on Conversations at first when I was trying to use omemo with myself for testing purposes.

**Comment by lovetox** [comment] 2016-07-28 14:11
what do you mean with adding yourself?
you added your own jid to your account?
this is not possible in gajim, you would get an error not allowing to add yourself.
for testing purposes you could just create a second jabber account and add that one

**Comment by herndlm** [comment] 2016-07-29 06:56
I think I did it on conversations and it also showed up on gajim or something like that. Maybe it was unrelated and I just saw my phone client in gajim, I'm not sure honestly.
But yes, I meant adding my own jid to my account.

**Comment by lovetox** [comment] 2016-07-29 12:56
we have to differentiate between two things

adding yourself like a contact, this should not ever happen, messages are probably lost due to the client not working correctly, not the plugin.

and

in gajim you see yourself as contact in the roster if another device of yours comes online.
if you click on it and open a chatwindow you will see a name like User/ResourceMobile for example
this is supported by the plugin and should work without a problem.
BUT you have to verify the fingerprints, in the fingerprint window beforehand, like with any other contact

**Comment by lovetox** [comment] 2016-07-29 13:35
i will close this issue

this issue stretches over multiple gajim versions, if there was a bug its probably solved until now.
there are many reasons why encrypted messages get "lost".

the first thing to check is:
- is the correct fingerprint trusted on **both** devices
- does messaging work when both devices are online, and stop if one is offline?
- if offline or syncing message history doesnt work, is my server supporting MAM? and does it actually work? test with not encrypted messages. beware receiving offline messages =/= MAM.

if that all is done, and you still cant get encryption working open an issue with a log

to get a log start gajim with
`-l gajim.plugin_system.omemo=DEBUG`

**Closed as completed** 2016-07-29 13:36 UTC
Labels: bug
