### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by gjedeer** [kalkin/gajim-omemo#43] opened 2016-02-11 12:19 UTC
- Gajim to gajim & Gajim to conversations: no encryption used on file transfer
- Conversations to Gajim: encrypted file is saved to disk - unreadable.

**Comment by cippaciong** [comment] 2016-02-12 09:12
Can be considered a duplicate of #19 ?
Long story short: for how Gajim is made right now, it's not easy for plugins to interoperate and this is something they should definitely be able to do in order to get this problem solved.

**Comment by gjedeer** [comment] 2016-02-12 10:31
Yeah, they're pretty close.

I'm making my first steps in Gajim code now and proposed this patch yesterday:

https://trac.gajim.org/ticket/8266

If they accept it, it should be possible to decrypt a file on disk once it's written, although I know it's far from perfect.

**Closed as completed** 2016-02-24 14:00 UTC
Labels: duplicate
