### ISSUE TITLE
Traceback when opening a second chat window for a contact but a different resource

### ISSUE THREAD

**Issue by enko** [kalkin/gajim-omemo#18] opened 2016-01-04 19:43 UTC
When a user is online with gajim and conversations, I open a chatwindow with him/her (double click on roster item), than I open a chatwindow to a specific resource (right click on the roster item, start chat, choose a resource) the following error is triggered:

```
Traceback (most recent call last):
  File "/home/tim/.local/share/gajim/plugins/omemo/ui.py", line 78, in on_click
    self.chat_control._show_lock_image(True, 'OMEMO', True, True, True)
  File "/usr/share/gajim/src/chat_control.py", line 2317, in _show_lock_image
    self.lock_image.set_from_file(img_path)
AttributeError: 'ChatControl' object has no attribute 'lock_image'
```

**Comment by kalkin** [comment] 2016-01-04 22:44
Thank you for reporting. This is a duplicate of #16

**Closed as completed by kalkin** 2016-01-04 22:44 UTC
Labels: duplicate
